spring:
  datasource:
    url: jdbc:sqlite:D:/PROJECTS/Mockr/mockr-keepr/mockr-keepr.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: com.mockr.runnr.config.SQLiteDialect
    properties:
      hibernate:
        format_sql: true # Pretty-print SQL
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8091
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
